import 'package:flutter/gestures.dart';
import 'package:little_kids_ai/core/common_imports.dart';
import 'package:little_kids_ai/widgets/common/app_web_view_screen.dart';

class TermsAgreementDialog extends StatelessWidget {
  final VoidCallback onAgree;

  const TermsAgreementDialog({
    super.key,
    required this.onAgree,
  });

  static Future<bool?> show(BuildContext context) {
    return showDialog<bool>(
      context: context,
      barrierDismissible: true,
      barrierColor: Colors.black.withOpacity(0.5),
      builder: (context) => TermsAgreementDialog(
        onAgree: () {
          Navigator.of(context).pop(true);
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    final screenWidth = mediaQuery.size.width;
    final isTablet = mediaQuery.size.shortestSide >= 600;

    return Center(
      child: Material(
        color: Colors.transparent,
        child: Container(
          width: isTablet
              ? (screenWidth * 0.65).clamp(420.0, 580.0)
              : (screenWidth * 0.78).clamp(320.0, 520.0),
          decoration: BoxDecoration(
            color: const Color(0xFFEFEFEF),
            borderRadius: BorderRadius.zero,
            border: Border.all(
              color: const Color(0xFF757575),
              width: 10,
            ),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.35),
                blurRadius: 16,
                offset: const Offset(0, 8),
              ),
            ],
          ),
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 14),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Inner Text Content
              RichText(
                textAlign: TextAlign.left,
                text: TextSpan(
                  style: GoogleFonts.nunito(
                    fontSize: 12.5,
                    height: 1.35,
                    fontWeight: FontWeight.w600,
                    color: const Color(0xFF1E293B),
                  ),
                  children: [
                    const TextSpan(
                      text:
                          "By using LittleLit, you agree to supervise your child's app usage. You must not generate explicit, offensive or violent content using the app, and you may not use the app to create stories featuring copyrighted or trademarked characters. You are not allowed to use any stories generated by LittleLit for public or commercial use. LittleLit monitors all prompts for ensuring the strictest compliance to these safety standards. For more details, click\n",
                    ),
                    TextSpan(
                      text: "Terms of Service",
                      style: GoogleFonts.nunito(
                        fontSize: 12.5,
                        fontWeight: FontWeight.w700,
                        color: const Color(0xFF0F172A),
                        decoration: TextDecoration.none,
                      ),
                      recognizer: TapGestureRecognizer()
                        ..onTap = () {
                          AppWebViewScreen.open(
                            context,
                            url: AppConstants.TERMS_URL,
                          );
                        },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),

              // Agree Button
              Center(
                child: SizedBox(
                  width: 220,
                  height: 40,
                  child: ElevatedButton(
                    onPressed: onAgree,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF357ABD),
                      elevation: 4,
                      shadowColor: Colors.black.withOpacity(0.35),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(6),
                      ),
                      padding: EdgeInsets.zero,
                    ),
                    child: Text(
                      "Agree",
                      style: GoogleFonts.nunito(
                        fontSize: 16,
                        fontWeight: FontWeight.w800,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
